name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  stream_parser:
    name: StreamParser Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version:
          - 3.0
          - 3.1
          - 3.2

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test